deploy:
  edge:
    branch: v1.8.47
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
script:
- bundle install
- bundle exec rake db:create
- bundle exec rake db:migrate
- bundle exec rspec
language: ruby
rvm:
- 2.6.2
addons:
  code_climate:
    repo_token: $REPO_TOKEN
services:
- postgresql
before_script:
- cp config/database.yml.travis config/database.yml
after_success:
- bundle exec codeclimate-test-reporter
